source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins
gem 'jekyll-admin', group: :jekyll_plugins

group :jekyll_plugins do
    gem "jekyll-feed", "~> 0.15.1"
end

#gem "minimal-mistakes-jekyll"

gem "webrick", "~> 1.7"
gem "kramdown-parser-gfm"